### ISSUE TITLE
Not able to intercept requests

### ISSUE THREAD

**Issue by anbusivam** [chmanie/wdio-intercept-service#103]
Hi, I am trying to use interceptor. Using chrome  83.0.4103.106.
browser.setupInterceptor();
...
browser.url(oDataUrl);   //this request goes through fine and also getting the response.
browser.pause(5000);
..
var irequest = browser.getRequest(0); //but this request fails
Getting error here "Could not find request with index 0". getRequests() returns an empty array. Am I missing something.  Kindly help.
Thanks

**Comment by chmanie** [comment]
Hey could you maybe post more code?

Is the request done when the website loads (i.e. before the first user interaction)?

**Comment by anbusivam** [comment]
Hi, I created a sample scenario which resulted in the same issue
- Defined a feature file as below
```
Feature: Use Interceptor demo
   Scenario: Use Interceptor
   Given I open some home page and set interceptor
   When I make browser to navigate to another url
   Then I should see the interceptor working
```
- Defined the code as below
```
const { Given, When, Then} = require('cucumber');
var chai = require('chai');
//var request = require('request-promise');
//const { get, post } = require('request-promise');
Given(/^I open some home page and set interceptor$/,function(){
    //browser.setupInterceptor(); this failed with error. "javascript error: Failed to read the 'sessionStorage' property from 'Window': Storage is disabled inside 'data:' URLs.""
    browser.url('https://www.google.com/');
    browser.pause(1000);
    browser.setupInterceptor();
})
When(/^I make browser to navigate to another url$/,function(){
    browser.url('https://www.google.co.in/');
    browser.pause(1000);
    console.log(browser.getRequests()); //this also returned empty array "[]"
    console.log(browser.getRequest(0)); //this has thrown error "Could not find request with index 0"
})
Then(/^I should see the interceptor working$/,function(){
    chai.expect(browser.getRequests().length > 0).to.be.true(); //this failed
    console.log('over');
})
```

**Comment by chmanie** [comment]
Yep, this is exactly the right behaviour. The interceptor can only watch on Ajax and fetch requests *after* any user interaction. In this case there is no user interaction (and probably not even ajax requests).

**Comment by chmanie** [comment]
Maybe I can try to help you here. What exactly are you trying to achieve?

**Comment by qatestingresearcher** [comment]
@anbusivam : Did it resolve?
@chmanie: I was trying the similar scenario,browser is making API calls but only for some executions browser.getRequests is returning the values rest it is returning []

Tried the below options, but not still facing the inconsistency in results. So I assume it should be something with the pause.
1. With the version wdio-intercept-service version 4.2.1 and 4.2.2
2. With  browser.getRequest({includingPending:true})
