### ISSUE TITLE
Any workaround when XHR uses Fetch

### ISSUE THREAD

**Issue by qburst-vipin** [chmanie/wdio-intercept-service#26]
Installed this plugin(3.0.0-beta.1) with webdriverio(4.6) and tried to access the XHR requests but getting empty response array

```
browser.setupInterceptor();
browser.click('//div[@class="src-containers-App-App-appContent"]/div/div/button');
browser.pause(1000);
var request = browser.getRequests();
console.log(request); //we are getting empty requests
```

I think [this](https://github.com/chmanie/webdriverajax/issues/19
) will be the issue - any workaround for this

![xhr](https://user-images.githubusercontent.com/12028913/42985025-3447ce3c-8c0d-11e8-838e-67a6fec373da.png)

**Comment by qburst-vipin** [comment]
This one worked for me
https://github.com/chmanie/webdriverajax/tree/feature/19-fetch-support

but method and response headers, body are getting empty, status code is showing.

```
url: 'https://test3-api.xxxxxxxxxx?clientID=xxxxxx',
    method: undefined,
    body: {},
    headers: {},
    response: { headers: {}, body: {}, statusCode: 200 } },
```

**Comment by chmanie** [comment]
I'm sorry, the PR is not done yet. I'll try to put that into a working state during the next couple of days

**Comment by qburst-vipin** [comment]
Much appreciated

**Comment by chmanie** [comment]
Sorry for the long wait. The package is now published under `wdio-intercept-service`, works with v5 of `webdriverio` and supports `fetch`
