### ISSUE TITLE
Can not find V2.x version in official npm registry

### ISSUE THREAD

**Issue by LNAmp** [chmanie/wdio-intercept-service#50]
Nowadays I try to use  WebDriverIO V4 and  wdio-intercept-service to do some web auto test. I noticed that WebDriverIO V4 only support wdio-intercept-service  V2.x but i can not find the V2.x in official npm registry. Cound you please upload some 2.x version to it ? Thanks a lot, appreciate!

**Comment by CubexsOne** [comment]
Hay Hay, this information is talking about the Branch "v2" in this repo.

This one: https://github.com/chmanie/wdio-intercept-service/tree/v2

**Comment by chmanie** [comment]
Hi! The v2 versions were called webdriverajax and are published here: https://www.npmjs.com/package/webdriverajax
