### ISSUE TITLE
URL is overridden if init object was used in fetch method

### ISSUE THREAD

**Issue by vrockai** [chmanie/wdio-intercept-service#51]
This line overrides the url field if an `init` object was passed to the fetch function:
https://github.com/chmanie/wdio-intercept-service/blame/master/lib/interceptor.js#L53

According to docs the `init.url` option doesn't exist:
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

It looks to me [the line overriding the url](https://github.com/chmanie/wdio-intercept-service/blame/master/lib/interceptor.js#L53) should be removed. With current state, I cannot get accessed URLs when using the `browser.getRequests()` function.

**Comment by lacell75** [comment]
I have the same problem.  Init overrides request.url, request.method and request.body while they can be "undefined". I will do a PR to override them only when the init values are not 'undefined'

```
[0-0] [
  {
    url: undefined,
    method: undefined,
    body: undefined,
    headers: {
      accept: 'application/json',
      authorization: 'Bearer 33a75a78-63f6-4d00-9580-1acb805eca38'
    },
    response: { headers: [Object], body: [], statusCode: 200 }
  },
  {
    url: undefined,
    method: 'POST',
    body: { text: '', excludedQueryIds: [], searchProfileName: null },
    headers: {
      accept: 'application/json',
      authorization: 'Bearer 33a75a78-63f6-4d00-9580-1acb805eca38',
      'content-type': 'application/json'
    },
    response: { headers: [Object], body: [Object], statusCode: 200 }
  },
  {
    url: undefined,
    method: undefined,
    body: undefined,
    headers: {
      accept: 'application/json',
      authorization: 'Bearer 33a75a78-63f6-4d00-9580-1acb805eca38'
    },
    response: { headers: [Object], body: [Object], statusCode: 200 }
  },
  {
    url: undefined,
    method: undefined,
    body: undefined,
    headers: {
      accept: 'application/json',
      authorization: 'Bearer 33a75a78-63f6-4d00-9580-1acb805eca38'
    },
    response: { headers: [Object], body: [], statusCode: 200 }
  },
]
```

**Comment by vrockai** [comment]
@lacell75 , there already is a PR for that https://github.com/chmanie/wdio-intercept-service/pull/53
I'm using the version from [my own fork](https://github.com/vrockai/wdio-intercept-service) for now and will switch back to original once it's merged or fix in a different way. If you want to use my fork, just state the dependency in the `package.json` like:
```
"wdio-intercept-service": "git+https://vrockai@github.com/vrockai/wdio-intercept-service.git"
```
but I would suggest creating your own fork with the fix, so you have full control over it.
