### ISSUE TITLE
do we have any example to initilize the serivce ?

### ISSUE THREAD

**Issue by bharat-dpd** [chmanie/wdio-intercept-service#62]
Hi 
I am failed to integrate this in my project. Can someone have any example ? I am following the README but failed to start this.
getting below error 
`browser.setupInterceptor is not a function`

**Comment by rvenk693** [comment]
it worked for me right off bat just had to do npm install and add service to wdio.conf as well as typescript conf file if you are using typescrpit . Then could use the brower.getRequest method in the test

**Comment by chmanie** [comment]
Hey!

I put up an example that you can fork an start from: https://github.com/chmanie/wdio-intercept-example
Or, if you're using TypeScript: https://github.com/chmanie/wdio-intercept-example-ts
