### ISSUE TITLE
intercept doc / files

### ISSUE THREAD

**Issue by kaufmann42** [chmanie/wdio-intercept-service#69]
It doesn't look like I'm able to intercept a downloaded file request. Is that possible? If not, it might make for a good feature.

**Comment by chmanie** [comment]
This library can only intercept ajax and fetch requests. In my opinion intercepting downloads is out of scope for this (and maybe impossible?). I'm sorry :(

**Comment by kaufmann42** [comment]
Gotcha. I know this isn't a help forum but if you think of a way to see file requests / downloads otherwise please let me know, otherwise thanks for the timely resoponse!
