### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by ksubramanian2** [chmanie/wdio-intercept-service#76]
I started using this service and it has been great. Thank you.
Is there any way it can be made to work on Internet Explorer too? 
I get this error on IE11:
Error executing JavaScript
[internet explorer  windows #1-0] javascript error: Error executing JavaScript
[internet explorer  windows #1-0]     at WebdriverAjax.setup at node_modules/wdio-intercept-service/index.js:41:22) 
Appreciate any hints.

**Comment by ksubramanian2** [comment]
Is there any specific polyfill I can add to get around this?

**Comment by chmanie** [comment]
It might be solved by the new version 4.1.0. Please try!

**Comment by ksubramanian2** [comment]
I tried with 4.1.0 still the same error:
 Error executing JavaScript
   at WebdriverAjax.setup (/node_modules/wdio-intercept-service/index.js:41:22)
   at Browser.next [as setupInterceptor] (/node_modules/@wdio/utils/build/monad.js:116:27)
   at loadQB (/trackstar.selenium.js:10:11)

**Comment by chmanie** [comment]
Then this must be another issue. It's sad that IE also doesn't report back the JS error. I don't have much time to look into this (especially as I don't have IE11 handy to test with). Please be patient, I will look into this eventually (or, feel free to dig deeper yourself - that would help tremendously).

**Comment by j-shiels** [comment]
if it helps, I have been using v3.1.1 with no issue on IE11.

**Comment by chmanie** [comment]
@j-shiels Well that might help indeed:

https://github.com/chmanie/wdio-intercept-service/compare/v3.1.1..v4.1.1#diff-5b8399b464e5e69f1be47740b4ce82de

I think it's the dangling comma. I'll make a change.

**Comment by chmanie** [comment]
Try version `wdio-intercept-service@4.1.2`, I feel like it should work again.

**Comment by ksubramanian2** [comment]
YES, 4.1.2 works for IE. Thanks a lot.
