### ISSUE TITLE
browser.getRequests() sample

### ISSUE THREAD

**Issue by ksubramanian2** [chmanie/wdio-intercept-service#77]
It would be nice to have a sample code for how to call browser.getRequests()
When I tried, it said the return value is not an array.

**Comment by chmanie** [comment]
Hey! There's lots of examples in the test files: https://github.com/chmanie/wdio-intercept-service/blob/master/test/spec/plugin_test.js#L121-L133

**Comment by chmanie** [comment]
This was an actual issue when the requests array was empty. 4.1.0 should fix that problem (not the fact that your array of captured requests was probably empty)

**Comment by ksubramanian2** [comment]
I was able to do browser.getRequests().length;
When I do a .filter, it said it was not an Array.  It looked like an iterable, but not array.
