### ISSUE TITLE
browser.setupInterceptor is not a function

### ISSUE THREAD

**Issue by Corinos** [chmanie/wdio-intercept-service#80]
`  "wdio-intercept-service": "^4.0.0",
    "webdriverajax": "^2.2.0",
    "webdriverio": "^5.18.7"`

I have a simple test I'm using to try to test the intercept service.  Thus far I've based it on the example here: https://webdriver.io/docs/wdio-intercept-service.html
```
describe('Test Intercept Service', () => {
     it('Intercept test', () => {
        browser.url('http://google.com');
        browser.setupInterceptor();
        var requests = browser.getRequests();
        console.log(requests);
    })
})
```

When I run the test, I get this error: `browser.setupInterceptor is not a function`
I've done the best basic troubleshooting I can, as I'm fairly new to JS and WDIO.  I've made sure it's using the right version of node, done a yarn install again and tried a few different combinations including putting it in a a browser.call statement.

**Comment by chmanie** [comment]
Hey!

You don't need to install `webdriverajax`, that's just the old version of this plugin.

I put up an example that you can fork an start from: https://github.com/chmanie/wdio-intercept-example
Or, if you're using TypeScript: https://github.com/chmanie/wdio-intercept-example-ts

**Comment by Corinos** [comment]
@chmanie When I copy and paste your example, it still fails the same way.  I'm using Jasmine.  Could that be a factor here?

**Comment by qualicion** [comment]
Hi I also tried the above example and I still kept getting `browser.setupInterceptor is not a function`. Is there anything that I need to try?

**Comment by chmanie** [comment]
Hey! Please try to start from this example, then subsequently add your tests: https://github.com/chmanie/wdio-intercept-example

To run the tests (you'll need Chrome 85, obviously you can add more browsers later):

```
git clone https://github.com/chmanie/wdio-intercept-example.git
npm install
npm test
```

Please let me know if you get an error with _just_ running these commands

**Comment by anthonygreen** [comment]
I'm encountering the same issue. 
Unfortunately the wdio-intercept-example project is now 4 years old and out-of-date. 
Is there a current "Hello World" example ?
