### ISSUE TITLE
First network call

### ISSUE THREAD

**Issue by ksubramanian2** [chmanie/wdio-intercept-service#94]
When using the sequence:
 browser.url(url);
 browser.setupInterceptor(); 

would it miss the first network call, if it happens quickly.
Is there a way to put in setupInterceptor before opening the url?

**Comment by lcombs15** [comment]
I second this. I believe I may actually be losing the first call in BrowserStack.

**Comment by chmanie** [comment]
Here's an extract from the readme:

> There's one catch though: you can't intercept HTTP calls that are initiated on page load (like in most SPAs), as it requires some setup work that can only be done after the page is loaded (due to limitations in selenium). That means you can just capture requests that were initiated inside a test. If you're fine with that, this plugin might be for you, so read on.

As far as I'm aware, it's not possible to inject code into a website before it's loaded. Sorry.
